workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: "stable"
      xcode: "latest"
    scripts:
      - name: "Install dependencies"
        script: |
          flutter pub get
      - name: "Build iOS app"
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - name: "iOS build"
        path: "build/ios/ipa"
    publishing:
      email:
        recipients:
          - "naznbd@icloud.com"
