workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release clean build
          mkdir -p build/ios/ipa
          xcrun -sdk iphoneos PackageApplication -v build/Release-iphoneos/Runner.app -o $(pwd)/build/ios/ipa/Runner.ipa
    artifacts:
      - name: iOS Build
        path: build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "naznbd@icloud.com"
        notify:
          success: true
          failure: true