workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: "stable"
      xcode: "latest"
    scripts:
      - name: "Install dependencies"
        script: |
          flutter pub get
      - name: "Build iOS app"
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release clean build -allowProvisioningUpdates
          mkdir -p build/ios/ipa
          xcrun -sdk iphoneos PackageApplication -v build/Release-iphoneos/Runner.app -o $(pwd)/build/ios/ipa/Runner.ipa
    artifacts:
      - name: "iOS build"
        path: "build/ios/ipa/*.ipa"
    publishing:
      email:
        recipients:
          - "naznbd@icloud.com"
