definitions:
  instance_mac_pro: &instance_mac_pro
    instance_type: mac_pro
    max_build_duration: 120
  env_versions: &env_versions
    flutter: stable
    xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
    cocoapods: default
  environment:
    automatic_ios_signing: &automatic_ios_signing
      groups:
        # Update the environment variables in the Codemagic UI below as required
        # APPLE_ID
        # APP_SPECIFIC_PASSWORD
        # APP_STORE_CONNECT_ISSUER_ID
        # APP_STORE_CONNECT_KEY_IDENTIFIER
        # APP_STORE_CONNECT_PRIVATE_KEY
        # APP_STORE_APP_ID
        # CERTIFICATE_PRIVATE_KEY
      vars:
        BUNDLE_ID: "com.nazim.mfsdbsdk"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        XCODE_CONFIG: "Release"
  artifacts:
    - &ipa build/ios/ipa/*.ipa
    - &xcode_log /tmp/xcodebuild_logs/*.log
    - &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    - &app $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  scripts:
    - &ios_initialize_keychain
      name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      script: |
        keychain initialize
    - &fetch_signing_files
      name: Fetch signing files
      script: |
        app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
    - &add_certs_to_keychain
      name: Add certs to keychain
      script: |
        keychain add-certificates
    - &use_profiles
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles
    - &increment_ios_build_number
      name: Increment build number
      script: |
        #!/bin/sh
        set -ex
        cd $FCI_BUILD_DIR
        # agvtool new-version -all $(($BUILD_NUMBER + 1))
        agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number $APP_STORE_APP_ID) + 1))
    - &build_ipa
      name: Build ipa
      script: |
        # xcode-project build-ipa --workspace $XCODE_WORKSPACE --scheme $XCODE_SCHEME --config $XCODE_CONFIG
        xcode-project build-ipa --workspace $XCODE_WORKSPACE --scheme $XCODE_SCHEME
  email_release: &email_release
    email:
      recipients:
        - "naznbd@icloud.com"
      notify:
        success: true
        failure: true
workflows:
  ios-release:
    name: iOS release
    <<: *instance_mac_pro
    environment:
      <<: *automatic_ios_signing
      <<: *env_versions
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - *increment_ios_build_number
      - *build_ipa
    artifacts:
      - *ipa
      - *dsym
    publishing:
      <<: *email_release
